import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";
import { StyledRoot } from "./styledRoot";
import Navbar from "./component/navbar";
import Footer from "./component/footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body style={{ margin: 0 }}>
        <StyledRoot>
          <AppRouterCacheProvider>
            <Navbar />
            <div>{children}</div>
            <Footer />
          </AppRouterCacheProvider>
        </StyledRoot>
      </body>
    </html>
  );
}
